cars/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from cars import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/', include('account.urls')),
    url(r'^', include('ess.urls')),

]

ess/urls.py
from django.conf.urls import url

from ess.views import BrandListView, ChassisListView, EngineListView, ECUListView, EcuDumpUploadView, \
    ECuDumpDownloadView, EcuDumpModifyView, OrgEcuDumpUploadView, OrgListFormView, OrgEcuDumpDownloadView, OrgEcuDumpModifyView, OrgEcuDumpDeleteView

urlpatterns = [
    url('^$',
        BrandListView.as_view(),
        name='brand-list'),
    url('^org-dump-upload/$',
        OrgEcuDumpUploadView.as_view(),
        name='org-ecu-dump-upload'),
    url('^org/$',
        OrgListFormView.as_view(),
        name='org-ecu-list'),
    url('^org/(?P<pk>\d+)/download/$',
        OrgEcuDumpDownloadView.as_view(),
        name='org-ecu-dump-download'),
    url('^org/(?P<pk>\d+)/modify/$',
        OrgEcuDumpModifyView.as_view(),
        name='org-ecu-dump-modify'),
    url('^org/(?P<pk>\d+)/delete/$',
        OrgEcuDumpDeleteView.as_view(),
        name='org-ecu-dump-delete'),
    url('^file/(?P<pk>\d+)/$',
        ECuDumpDownloadView.as_view(),
        name='download-ecu-mod'),
    url('^file/(?P<pk>\d+)/modify/$',
        EcuDumpModifyView.as_view(),
        name='modify-ecu-dump'),
    url('^(?P<brand>\w+)/$',
        ChassisListView.as_view(),
        name='chassis-list'),
    url('^(?P<brand>\w+)/(?P<chassis>\w+)/$',
        EngineListView.as_view(),
        name='car-model-list'),
    url('^(?P<brand>\w+)/(?P<chassis>\w+)/(?P<engine>[\w\.\-]+)/$',
        ECUListView.as_view(),
        name='ecu-list'),
    url('^(?P<brand>\w+)/(?P<chassis>\w+)/(?P<engine>[\w\.\-]+)/(?P<ecu>\w+)/$',
        EcuDumpUploadView.as_view(),
        name='ecu-dump-form'),
    url('^(?P<brand>\w+)/(?P<chassis>\w+)/(?P<engine>[\w\.\-]+)/(?P<ecu>\w+)/(?P<script>\d+)/$',
        EcuDumpUploadView.as_view(),
        name='ecu-dump-upload'),
    # url('^(?P<brand>\w+)/(?P<chassis>\w+)/(?P<engine>[\w\.\-]+)/(?P<ecu>\w+)/upload/(?P<ecu_id>\d+)/(?P<id>\d+)/$',
    #     ModificationListView.as_view(),
    #     name='modification-upload'),
]

ess/models.py
from django.contrib.auth.models import User
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Chassis(models.Model):
    brand = models.ForeignKey(Brand)
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "{} / {}".format(self.brand, self.name)


class Engine(models.Model):
    chassis = models.ForeignKey(Chassis)
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return "{} / {}".format(self.chassis, self.name)


class EcuMessage(models.Model):
    message = models.TextField()

    def __str__(self):
        return self.message[:50]


class ECU(models.Model):
    engine = models.ForeignKey(Engine)
    name = models.CharField(max_length=50)
    message = models.ForeignKey(EcuMessage, null=True, blank=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return "{} / {}".format(self.engine, self.name)


class Modification(models.Model):
    name = models.CharField(max_length=10)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class SoftwareVersion(models.Model):
    name = models.CharField(max_length=20)
    ecu = models.ForeignKey(ECU)

    def __str__(self):
        return '{} / {}'.format(self.ecu, self.name)

    class Meta:
        unique_together = ('name', 'ecu',)


class ModScript(models.Model):
    ecu = models.ManyToManyField(ECU)
    sw = models.ManyToManyField(SoftwareVersion)
    modification = models.ForeignKey(Modification)
    name = models.CharField(max_length=50)
    script = models.TextField()

    def __str__(self):
        return self.name


class EcuDumpPayload(models.Model):
    content = models.BinaryField()


class EcuDump(models.Model):
    user = models.ForeignKey(User)
    ecu = models.ForeignKey(ECU)
    name = models.CharField(max_length=50)
    sw = models.ForeignKey(SoftwareVersion)
    modified = models.BooleanField()
    parent = models.ForeignKey('self', null=True, blank=True)
    file = models.OneToOneField(EcuDumpPayload)
    messages = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def message_list(self):
        return self.messages.split('\n')

    def __str__(self):
        return self.name


class OrgEcuDumpPayload(models.Model):
    content = models.BinaryField()


class OrgEcuDump(models.Model):
    ecu = models.ForeignKey(ECU)
    sw = models.CharField(max_length=50, blank=True)
    hw = models.CharField(max_length=50, blank=True)
    file = models.OneToOneField(OrgEcuDumpPayload)
    date = models.DateTimeField(auto_now_add=True)
    size = models.IntegerField()

    class Meta:
        ordering = ['-date']


class ValidationScript(models.Model):
    ecu = models.OneToOneField(ECU)
    name = models.CharField(max_length=50)
    script = models.TextField()

    def __str__(self):
        return self.name

ess/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, View, FormView, DeleteView

from .forms import EcuDumpUploadForm, EcuDumpModifyForm, OrgEcuDumpUploadForm, OrgEcuDumpSearchForm, \
    OrgEcuDumpModifyForm
from .models import Brand, Chassis, Engine, ECU, EcuDump, SoftwareVersion, EcuDumpPayload, OrgEcuDump, OrgEcuDumpPayload


class BrandListView(ListView):
    model = Brand


class ChassisListView(ListView):
    model = Chassis

    def get_queryset(self):
        return Chassis.objects.filter(brand__name=self.kwargs['brand']).select_related()


class EngineListView(ListView):
    model = Engine

    def get_queryset(self):
        return Engine.objects.filter(
            chassis__brand__name=self.kwargs['brand']).filter(
            chassis__name=self.kwargs['chassis']).select_related()


class ECUListView(ListView):
    model = ECU

    def get_queryset(self):
        return ECU.objects.filter(
            engine__chassis__brand__name=self.kwargs['brand']).filter(
            engine__chassis__name=self.kwargs['chassis']).filter(
            engine__name=self.kwargs['engine']
        ).select_related()


class EcuDumpUploadView(LoginRequiredMixin, FormView):
    form_class = EcuDumpUploadForm
    template_name = 'ess/ecu_dump_upload.html'
    success_url = reverse_lazy('file-list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            software_version = SoftwareVersion.objects.filter(ecu=self.kwargs['ecu'], name=form.cleaned_data.get('sw'))
            if software_version:
                request.FILES['file'].seek(0)
                EcuDump.objects.create(user=request.user, ecu=self.kwargs['ecu'], sw=software_version[0],
                                       name=form.cleaned_data.get('name'), modified=False,
                                       file=EcuDumpPayload.objects.create(content=form.cleaned_data.get('file').read()))
                return self.form_valid(form)
            else:
                messages.warning(request, 'There was an internal error. Please contact support about your SW.')
        return self.form_invalid(form)

    def get_initial(self):
        self.kwargs['ecu'] = ECU.objects.filter(
            engine__chassis__brand__name=self.kwargs['brand']).filter(
            engine__chassis__name=self.kwargs['chassis']).filter(
            engine__name=self.kwargs['engine']).filter(
            name=self.kwargs['ecu']).select_related().get()
        script_id = self.kwargs['ecu'].validationscript.id
        return {'script': script_id}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ecu'] = self.kwargs['ecu']
        return context


class OrgEcuDumpUploadView(UserPassesTestMixin, FormView):
    form_class = OrgEcuDumpUploadForm
    template_name = 'ess/org_ecu_dump_upload.html'
    success_url = reverse_lazy('org-ecu-list')

    def test_func(self):
        return self.request.user.is_superuser

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            OrgEcuDump.objects.create(ecu=form.cleaned_data['ecu'], sw=form.cleaned_data['sw'],
                                      hw=form.cleaned_data['hw'],
                                      size=form.cleaned_data.get('file').size,
                                      file=OrgEcuDumpPayload.objects.create(
                                          content=form.cleaned_data.get('file').read()))
            return self.form_valid(form)
        return self.form_invalid(form)


class OrgEcuDumpModifyView(UserPassesTestMixin, FormView):
    form_class = OrgEcuDumpModifyForm
    template_name = 'ess/org_ecu_dump_upload.html'
    success_url = reverse_lazy('org-ecu-list')

    def test_func(self):
        return self.request.user.is_superuser

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            org_ecu_dump = OrgEcuDump.objects.get(pk=self.kwargs['pk'])
            if form.cleaned_data['sw']:
                org_ecu_dump.sw = form.cleaned_data['sw']
            if form.cleaned_data['hw']:
                org_ecu_dump.hw = form.cleaned_data['hw']
            if form.cleaned_data['ecu']:
                org_ecu_dump.ecu = form.cleaned_data['ecu']
            if form.cleaned_data['file']:
                org_ecu_dump.size = form.cleaned_data['file'].size
                org_ecu_dump.file = OrgEcuDumpPayload.objects.create(
                    content=form.cleaned_data['file'].read())
            org_ecu_dump.save()
            return self.form_valid(form)
        return self.form_invalid(form)

    def get_initial(self):
        org_ecu_dump = OrgEcuDump.objects.select_related().get(pk=self.kwargs['pk'])
        return {'sw': org_ecu_dump.sw, 'hw': org_ecu_dump.sw, 'ecu': org_ecu_dump.ecu}


class OrgEcuDumpDeleteView(UserPassesTestMixin, DeleteView):
    model = OrgEcuDump
    success_url = reverse_lazy('org-ecu-list')

    def test_func(self):
        return self.request.user.is_superuser


class EcuDumpModifyView(LoginRequiredMixin, FormView):
    form_class = EcuDumpModifyForm
    template_name = 'ess/ecu_dump_modify.html'
    success_url = reverse_lazy('file-list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            ecu_dump = EcuDump.objects.get(pk=self.kwargs['pk'])
            content = ecu_dump.file.content
            script_messages = ''
            modifications_made = ''
            for mod_script in ecu_dump.ecu.modscript_set.filter(sw=ecu_dump.sw):
                if form.cleaned_data.get(mod_script.modification.name):
                    temp_env = {}
                    exec(mod_script.script, temp_env)
                    content, script_message, error = temp_env['make_change'](content, ecu_dump.sw.name)
                    script_messages += script_message + '\n'
                    if error:
                        messages.error(request, script_message)
                    else:
                        messages.success(request, script_message)
                        modifications_made += mod_script.modification.name
            EcuDump.objects.create(user=request.user, ecu=ecu_dump.ecu, sw=ecu_dump.sw, parent=ecu_dump,
                                   name="{}_{}".format(ecu_dump.name, modifications_made), modified=True,
                                   file=EcuDumpPayload.objects.create(content=content),
                                   messages=script_messages.strip())
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.ecu_dump = EcuDump.objects.select_related().get(pk=self.kwargs['pk'])
        mod_scripts = self.ecu_dump.ecu.modscript_set.filter(sw=self.ecu_dump.sw).select_related()
        kwargs['mods'] = [mod_script.modification for mod_script in mod_scripts]

        return kwargs

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['ecu_message'] = self.ecu_dump.ecu.message
        return kwargs


class ECuDumpDownloadView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            ecu_dump = get_object_or_404(EcuDump, pk=self.kwargs['pk'])
        else:
            ecu_dump = get_object_or_404(EcuDump, pk=self.kwargs['pk'], user=request.user)
        filename = ecu_dump.name
        response = HttpResponse(content_type='application/octet-stream', content=ecu_dump.file.content)
        response["Content-Disposition"] = "attachment; filename={}".format(filename)
        return response


class OrgListFormView(LoginRequiredMixin, FormView):
    form_class = OrgEcuDumpSearchForm
    template_name = 'ess/org_ecu_dump_list.html'
    success_url = reverse_lazy('file-list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            kwargs = self.get_context_data()
            query = kwargs['orgs']
            hw = form.cleaned_data['hw'].strip()
            sw = form.cleaned_data['sw'].strip()
            brand = form.cleaned_data['brand'].strip()
            chassis = form.cleaned_data['chassis'].strip()
            engine = form.cleaned_data['engine'].strip()
            if hw:
                query = query.filter(hw__icontains=hw)
            if sw:
                query = query.filter(sw__icontains=sw)
            if brand:
                query = query.filter(ecu__engine__chassis__brand__name__icontains=brand)
            if chassis:
                query = query.filter(ecu__engine__chassis__name__icontains=chassis)
            if engine:
                query = query.filter(ecu__engine__name__icontains=engine)
            kwargs['orgs'] = query
            return self.render_to_response(kwargs)
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['orgs'] = OrgEcuDump.objects.defer('file').select_related().order_by(
            'ecu__engine__chassis__brand__name', 'ecu__engine__chassis__name', 'ecu__engine__name', 'ecu__name').all()
        return kwargs


class OrgEcuDumpDownloadView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        dump = get_object_or_404(OrgEcuDump.objects.select_related(), pk=self.kwargs['pk'])
        response = HttpResponse(content_type='application/octet-stream', content=dump.file.content)
        response["Content-Disposition"] = "attachment; filename={}-{}-{}-{}-{}-{}.org".format(

templates/ess/OLD_modification_list.html
{% extends "base.html" %}
{% block main %}
  <h1>Modification</h1>
  <ul>
    <li>
      {% for script in object_list %}
        <form action="{% url 'modification-upload' ecu.engine.chassis.brand.name ecu.engine.chassis.name ecu.engine.name ecu.name ecu.id script.id %}" method="post" enctype="multipart/form-data">
          <h2>{{ script.modification }}</h2>
          {% csrf_token %}
          <p>{{ form.non_field_errors }}</p>
          <p>{{ form.file.label_tag }} {{ form.file.help_text }}</p>
          <p>
            {{ form.file.errors }}
            {{ form.file }}
          </p>
          <p>{{ form.name.label_tag }} {{ form.name.help_text }}</p>
          <p>
            {{ form.name.errors }}
            {{ form.name }}
          </p>
          <input type="hidden" name="ecu" value="{{ ecu }}" id="id_ecu"/>
          <p><input type="submit" value="Upload"/></p>
        </form>
        </li>
      {% empty %}
        <li>No Modification yet.</li>
      {% endfor %}
  </ul>
{% endblock %}

templates/ess/brand_list.html
{% extends "base.html" %}
{% block main %}
  <ul class="breadcrumb">
    <li class="active">Brands</li>
  </ul>
  <h1>Brands</h1>
  <div class="btn-group-vertical">
    {% for brand in object_list %}
      <a class="btn btn-default" href="{% url 'chassis-list' brand %}">{{ brand }}</a>
    {% empty %}
      <p class="lead">No Brands yet.</p>
    {% endfor %}
  </div>


{% endblock %}

templates/ess/chassis_list.html
{% extends "base.html" %}
{% block main %}
  <ul class="breadcrumb">
    <li><a href="{% url 'brand-list' %}">Brands</a></li>
    <li class="active">Chassis</li>
  </ul>
  <h1>Chassis</h1>
  <div class="btn-group-vertical">
    {% for chassis in object_list %}
      <a class="btn btn-default" href="{% url 'car-model-list' chassis.brand.name chassis.name %}">{{ chassis }}</a>
    {% empty %}
      <p class="lead">No chassis yet.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/ess/ecu_dump_modify.html
{% extends "base.html" %}
{% block main %}

  {% if ecu_message %}
  <div class="alert alert-warning" role="alert">{{ ecu_message.message|linebreaksbr }}</div>
  {% endif %}

  {% load crispy_forms_tags %}
  {% crispy form %}

{% endblock %}

templates/ess/ecu_dump_upload.html
{% extends "base.html" %}
{% block main %}

  <ul class="breadcrumb">
    <li><a href="{% url 'brand-list' %}">Brands</a></li>
    <li><a href="{% url 'chassis-list' ecu.engine.chassis.brand.name %}">Chassis</a></li>
    <li><a href="{% url 'car-model-list' ecu.engine.chassis.brand.name ecu.engine.chassis.name%}">Engine</a></li>
    <li><a href="{% url 'ecu-list' ecu.engine.chassis.brand.name ecu.engine.chassis.name ecu.engine.name %}">Ecu</a></li>
    <li class="active">Upload</li>
  </ul>

  <div class="panel panel-default">
    <div class="panel-heading">Please upload an Ecu dump file</div>
    <div class="panel-body">
      {% load crispy_forms_tags %}
      {% crispy form %}
    </div>
  </div>


{% endblock %}

templates/ess/ecu_list.html
{% extends "base.html" %}
{% block main %}
  <ul class="breadcrumb">
    <li><a href="{% url 'brand-list' %}">Brands</a></li>
    <li><a href="{% url 'chassis-list' object_list.0.engine.chassis.brand.name %}">Chassis</a></li>
    <li><a href="{% url 'car-model-list' object_list.0.engine.chassis.brand.name object_list.0.engine.chassis.name%}">Engine</a></li>
    <li class="active">ECU</li>
  </ul>
  <h1>ECU</h1>
  <div class="btn-group-vertical">
    {% for ecu in object_list %}
      {% if ecu.validationscript %}
        <a class="btn btn-default"
           href="{% url 'ecu-dump-form' ecu.engine.chassis.brand.name ecu.engine.chassis.name ecu.engine.name ecu.name %}">{{ ecu }}</a>
      {% endif %}
    {% empty %}
      <p class="lead">No Ecus yet.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/ess/engine_list.html
{% extends "base.html" %}
{% block main %}
  <ul class="breadcrumb">
    <li><a href="{% url 'brand-list' %}">Brands</a></li>
    <li><a href="{% url 'chassis-list' object_list.0.chassis.brand.name %}">Chassis</a></li>
    <li class="active">Engine</li>
  </ul>
  <h1>Engine</h1>
  <div class="btn-group-vertical">
    {% for engine in object_list %}
      <a class="btn btn-default"
         href="{% url 'ecu-list' engine.chassis.brand.name engine.chassis.name engine.name %}">{{ engine }}</a>

    {% empty %}
      <p class="lead">No Car Models yet.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/ess/modification_detail.html
{% extends "base.html" %}
{% block main %}
  <h1>{{ object.name }}</h1>
  <form action="{% url 'modification-upload' object.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    <p>{{ form.file.label_tag }} {{ form.file.help_text }}</p>
    <p>
      {{ form.file.errors }}
      {{ form.file }}
    </p>
    <p><input type="submit" value="Upload"/></p>
  </form>
  <pre>{{ object.script }}</pre>
{% endblock %}

templates/ess/org_ecu_dump_list.html
{% extends "base.html" %}
{% block main %}

  <ul class="breadcrumb">
    <li class="active">ORI Files</li>
  </ul>

  <div class="panel panel-default">
    <div class="panel-heading">Search</div>
    <div class="panel-body">
      {% load crispy_forms_tags %}
      {% crispy form %}
    </div>
  </div>

  <table class="table table-striped table-hover ">

    <thead>
      <tr>
        <th>BRAND</th>
        <th>CHASSIS</th>
        <th>ENGINE</th>
        <th>ECU</th>
        <th>HW</th>
        <th>SW</th>
        <th>SIZE</th>
        <th>ACTIONS</th>
      </tr>
    </thead>

    <tbody>

      {% for org in orgs %}
        <tr>
          <td>{{ org.ecu.engine.chassis.brand.name }}</td>
          <td>{{ org.ecu.engine.chassis.name }}</td>
          <td>{{ org.ecu.engine.name }}</td>
          <td>{{ org.ecu.name }}</td>
          <td>{{ org.hw }}</td>
          <td>{{ org.sw }}</td>
          <td>{{ org.size|filesizeformat }}</td>
          <td>
            <a class="btn btn-default" href="{% url 'org-ecu-dump-download' org.pk %}">Download</a>
            {% if user.is_superuser %}
              <a class="btn btn-default" href="{% url 'org-ecu-dump-modify' org.pk %}">Modify</a>
              <a class="btn btn-warning" href="{% url 'org-ecu-dump-delete' org.pk %}">Delete</a>
            {% endif %}
          </td>
        </tr>
      {% empty %}
        <p class="lead">No Original Ecu Dumps found.</p>
      {% endfor %}

    </tbody>

  </table>

{% endblock %}

templates/ess/org_ecu_dump_upload.html
{% extends "base.html" %}
{% block main %}

  <ul class="breadcrumb">
    <li class="active">Upload</li>
  </ul>

  <div class="panel panel-default">
    <div class="panel-heading">Please upload an original Ecu dump file</div>
    <div class="panel-body">
      {% load crispy_forms_tags %}
      {% crispy form %}
    </div>
  </div>

{% endblock %}

templates/ess/orgecudump_confirm_delete.html
{% extends "base.html" %}
{% block main %}

  <ul class="breadcrumb">
    <li class="active">Delete</li>
  </ul>

  <div class="panel panel-default">
    <div class="panel-heading">Please upload an original Ecu dump file</div>
    <div class="panel-body">
      <form  action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="alert alert-danger" role="alert">Are you sure you want to delete this file?</div>
        </div>
        <button type="submit" class="btn btn-default">Delete</button>
      </form>
    </div>
  </div>

{% endblock %}